version: "3.3"
services:
  api:
    depends_on:
      - postgres
      - minio
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    entrypoint: /start-reload.sh
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/postgres
      ENVIRONMENT: DEVELOPMENT
      SECRET_KEY: "8d8d10fbbe8cebd583658d620baff55aa606cd135f5193851a113a0ece1912d4"
      AWS_ACCESS_KEY: minio
      AWS_SECRET_KEY: miniopassword
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: admin
  minio:
    image: minio/minio:latest
    volumes:
      - minio_volume:/minio_data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopassword
    command: server /minio_data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio_volume: