version: "3.3"
services:
  api:
    depends_on:
      - postgres
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    entrypoint: /start-reload.sh
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/postgres
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: admin