"""Create books table

Revision ID: 1af58ee2f3cf
Revises: 35f1afa9c983
Create Date: 2021-03-03 23:55:14.594419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1af58ee2f3cf"
down_revision = "35f1afa9c983"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
