"""Add name column to user

Revision ID: 35f1afa9c983
Revises: 8ad389da93ef
Create Date: 2021-03-03 22:43:22.994060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35f1afa9c983"
down_revision = "8ad389da93ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###
