"""Add cover field to book

Revision ID: 6478173b7f5d
Revises: cda51509be90
Create Date: 2021-03-04 02:31:51.842912

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6478173b7f5d"
down_revision = "cda51509be90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("cover_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "cover_url")
    # ### end Alembic commands ###
