"""Create banned users table

Revision ID: 935aae512b1d
Revises: 2fd423e65ebe
Create Date: 2021-03-06 21:11:12.541655

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "935aae512b1d"
down_revision = "2fd423e65ebe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banned_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_banned_users_email"), "banned_users", ["email"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_banned_users_email"), table_name="banned_users")
    op.drop_table("banned_users")
    # ### end Alembic commands ###
