"""Added sold and marked_for_delete fields

Revision ID: a6dcafc31446
Revises: 935aae512b1d
Create Date: 2021-05-14 00:46:19.437383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6dcafc31446"
down_revision = "935aae512b1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("marked_for_delete", sa.Boolean(), nullable=True))
    op.execute("UPDATE books SET marked_for_delete = false")
    op.add_column("books", sa.Column("sold", sa.Boolean(), nullable=True))
    op.execute("UPDATE books SET sold = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "sold")
    op.drop_column("books", "marked_for_delete")
    # ### end Alembic commands ###
