"""Add foreign key to book table

Revision ID: cda51509be90
Revises: 1af58ee2f3cf
Create Date: 2021-03-04 00:07:12.420531

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cda51509be90"
down_revision = "1af58ee2f3cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "books", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "owner_id")
    # ### end Alembic commands ###
